// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type CreateAccountInput struct {
	Username string `json:"username"`
}

type CreateItemInput struct {
	Title     string `json:"title"`
	Content   string `json:"content"`
	AccountID string `json:"accountId"`
}

type Item struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	AccountID string `json:"accountId"`
	UpdatedAt string `json:"updatedAt"`
	CreatedAt string `json:"createdAt"`
}

type UpdateAccountInput struct {
	Username *string `json:"username,omitempty"`
}

type UpdateItemInput struct {
	Title     *string `json:"title,omitempty"`
	Content   *string `json:"content,omitempty"`
	AccountID *string `json:"accountId,omitempty"`
}
