import { Inter } from 'next/font/google'
import RideMateHeader from '@/components/header/header'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    return (
      <html lang="ja">
        <body className={inter.className}>
          {/* 全体背景色設定 */}
          <div className='min-h-screen bg-gray-100'>
            <RideMateHeader/>
            <div className="main-container">
              {children}
            </div>
          </div>
        </body>
      </html>
    )
}