import { Inter } from 'next/font/google'
import RideMateHeader from '@/components/header/header'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    return (
      <html lang="ja">
        <head>
          <script src="https://embed.zenn.studio/js/listen-embed-event.js"></script>
        </head>
        <body className={inter.className}>
          {/* 全体背景色設定 */}
          <div className='min-h-screen bg-gray-100 flex flex-col'>
            <RideMateHeader/>
              <div className="main-container">
                {children}
              </div>
          </div>
        </body>
      </html>
    )
}